/**
  You need to create an express HTTP server in Node.js which will handle the logic of a todo list app.
  - Don't use any database, just store all the data in an array to store the todo list data (in-memory)
  - Hard todo: Try to save responses in files, so that even if u exit the app and run it again, the data remains (similar to databases)

  Each todo has a title and a description. The title is a string and the description is a string.
  Each todo should also get an unique autogenerated id every time it is created
  The expected API endpoints are defined below,
  1.GET /todos - Retrieve all todo items
    Description: Returns a list of all todo items.
    Response: 200 OK with an array of todo items in JSON format.
    Example: GET http://localhost:3000/todos
    
  2.GET /todos/:id - Retrieve a specific todo item by ID
    Description: Returns a specific todo item identified by its ID.
    Response: 200 OK with the todo item in JSON format if found, or 404 Not Found if not found.
    Example: GET http://localhost:3000/todos/123
    
  3. POST /todos - Create a new todo item
    Description: Creates a new todo item.
    Request Body: JSON object representing the todo item.
    Response: 201 Created with the ID of the created todo item in JSON format. eg: {id: 1}
    Example: POST http://localhost:3000/todos
    Request Body: { "title": "Buy groceries", "completed": false, description: "I should buy groceries" }
    
  4. PUT /todos/:id - Update an existing todo item by ID
    Description: Updates an existing todo item identified by its ID.
    Request Body: JSON object representing the updated todo item.
    Response: 200 OK if the todo item was found and updated, or 404 Not Found if not found.
    Example: PUT http://localhost:3000/todos/123
    Request Body: { "title": "Buy groceries", "completed": true }
    
  5. DELETE /todos/:id - Delete a todo item by ID
    Description: Deletes a todo item identified by its ID.
    Response: 200 OK if the todo item was found and deleted, or 404 Not Found if not found.
    Example: DELETE http://localhost:3000/todos/123

    - For any other route not defined in the server return 404

  Testing the server - run `npm run test-todoServer` command in terminal
 */
const express = require('express');
const bodyParser = require('body-parser');
const cors = require('cors');
const app = express();
const PORT = 3000;
const fs = require('fs');

app.use(cors());
app.use(bodyParser.json());

// Get all todos
app.get('/todos', (req, res) => {
  fs.readFile('data.json', 'UTF-8', (err, data) => {
    if (err) console.log('not able to read file');
    return res.status(200).json(JSON.parse(data));
  });
});

// Get todo with particular ID
app.get('/todos/:id', (req, res) => {
  const id = parseInt(req.params.id);
  fs.readFile('data.json', 'UTF-8', (err, data) => {
    if (err) console.log('not able to read file');
    const todos = JSON.parse(data);
    const todo = todos.find((a) => a.id === id);
    if (todo) {
      return res.status(200).json(todo);
    } else {
      return res.status(404).json({message: 'No todo present with such id'});
    }
  });
})

// post todo
app.post('/todos', (req, res) => {
  const {title, description} = req.body;
  const id = new Date().getTime();

  fs.readFile('data.json', 'UTF-8', (err, data) => {
    if (err) console.log('file not found');
    const todos = JSON.parse(data);
    const todo = {
      title, description, id
    }
    todos.push(todo);
    fs.writeFile('data.json', JSON.stringify(todos), 'UTF-8', (err, data) => {
      if (data) return res.status(201).json({id: id});;
    })
  })
})

// post todo
app.put('/todos/:id', (req, res) => {
  const {title, description} = req.body;
  const id = parseInt(req.params.id);

  fs.readFile('data.json', 'UTF-8', (err, data) => {
    if (err) console.log('file not found');
    const todos = JSON.parse(data);
    const todoIndex = todos.findIndex((a) => a.id === id);
    if (todoIndex < 0) return res.status(404).json({message: 'Todo ID not found'});
    const updatedTodo = {
      title, description, id
    }
    todos[todoIndex] = updatedTodo; 
    res.status(200).json({message: 'todo item was updated'})
    fs.writeFile('data.json', JSON.stringify(todos), 'UTF-8', (err, data) => {
      if (data) return;
    })
  })
})

app.delete('/todos/:id', (req, res) => {
  const id = parseInt(req.params.id);

  fs.readFile('data.json', 'UTF-8', (err, data) => {
    const todos = JSON.parse(data);
    const todoIndex = todos.find((a) => a.id === id);

    if (!todoIndex) return res.status(400).json({message: 'Todo ID not found'});

    const filterTodo = todos.filter((a) => a.id !== id);
    if (filterTodo) res.status(200).json({message: 'Todo item deleted'});

    fs.writeFile('data.json', JSON.stringify(filterTodo), 'UTF-8', (err, data) => {
      if (data) return;
    })

  })
})

app.listen(PORT,() => {
  console.log(`App listening on port ${PORT}`)
});

module.exports = app;
